### ISSUE TITLE
Simpler log folder structure

### ISSUE THREAD

**Issue by julian-molina** [AdvancedAlgos/AACloud#11]
AACloud creates the following folder structure in order to separately store logs from different executions:

LOGS > YEAR > MONTH > DAY > HOUR > MINUTE > SECOND > ...

The same goal can be achieved by using the same string to name one single folder instead:

LOGS > YEAR-MONTH-DAY-HOUR-MINUTE-SECOND > ...

This would make logs a lot easier to access and use in general.

**Comment by Luis-Fernando-Molina** [comment]
done.
