### ISSUE TITLE
Bot not running from the browser

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/AACloud#22]
![image](https://user-images.githubusercontent.com/9479367/47279377-e6fc2c00-d5d0-11e8-9660-9c4f9f993451.png)

This NULL value is preventing a bot to run. 

![image](https://user-images.githubusercontent.com/9479367/47279398-157a0700-d5d1-11e8-86db-6269acc76959.png)

This is what it can be seen at the logs.

![image](https://user-images.githubusercontent.com/9479367/47279406-232f8c80-d5d1-11e8-91a1-ae3cd0e58e89.png)

There is no authentication token...

**Comment by matbenitez** [comment]
The local storage variable name was changed from auth0Token  to access_token when we implement the MasterApp. Change the value on project AAWeb, file ExchangeAPI.

**Comment by Luis-Fernando-Molina** [comment]
Corrected al AAWeb
