### ISSUE TITLE
ERROR trying to delete log loop folders

### ISSUE THREAD

**Issue by julian-molina** [AdvancedAlgos/AACloud#4]
**Node.js console is constantly logging the following type of errors:**

Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AAOlivia.1.0/Multi-Period-Daily/Loop.626.Reading file 2018-04-19-08-36---414682---1.Status Report.AABruce.One-Min-Daily-Candles-Volumes.2018.04.log. err.message = ENOTEMPTY: directory not empty, rmdir 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AAOlivia.1.0\Multi-Period-Daily\Loop.626'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AAOlivia.1.0/Multi-Period-Daily/Loop.626.Reading file 2018-04-19-08-36---414682---1.Status Report.AABruce.One-Min-Daily-Candles-Volumes.2018.04.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AAOlivia.1.0\Multi-Period-Daily\Loop.626\2018-04-18-21-04---262319---1.Indicator Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AAOlivia.1.0/Multi-Period-Daily/Loop.626.Reading file 2018-04-19-08-36---852109---1.Blob Storage.AAMasters.AAOlivia.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AAOlivia.1.0\Multi-Period-Daily\Loop.626\2018-04-18-21-04---262319---1.Indicator Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AAOlivia.1.0/Multi-Period-Daily/Loop.626.Reading file 2018-04-19-08-36---852109---1.Blob Storage.AAMasters.AAOlivia.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AAOlivia.1.0\Multi-Period-Daily\Loop.626\2018-04-18-21-04---262319---1.Indicator Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AAOlivia.1.0/Multi-Period-Daily/Loop.626.Reading file 2018-04-19-08-36---9207---1.Status Dependencies.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AAOlivia.1.0\Multi-Period-Daily\Loop.626\2018-04-18-21-04---262319---1.Indicator Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AAOlivia.1.0/Multi-Period-Daily/Loop.626.Reading file 2018-04-19-08-36---9207---1.Status Dependencies.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AAOlivia.1.0\Multi-Period-Daily\Loop.626\2018-04-18-21-04---262319---1.Indicator Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AAOlivia.1.0/Multi-Period-Daily/Loop.626.Reading file 2018-04-19-08-36---414682---1.Status Report.AABruce.One-Min-Daily-Candles-Volumes.2018.04.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AAOlivia.1.0\Multi-Period-Daily\Loop.626\2018-04-18-21-04---262319---1.Indicator Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AAOlivia.1.0/Multi-Period-Daily/Loop.626.Reading file 2018-04-19-08-36---414682---1.Status Report.AABruce.One-Min-Daily-Candles-Volumes.2018.04.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AAOlivia.1.0\Multi-Period-Daily\Loop.626\2018-04-18-21-04---262319---1.Indicator Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AABruce.1.0/One-Min-Daily-Candles-Volumes/2018/04/Loop.681.Reading file 2018-04-19-08-37---965005---1.Status Report.AABruce.One-Min-Daily-Candles-Volumes.2018.04.log. err.message = ENOTEMPTY: directory not empty, rmdir 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AABruce.1.0\One-Min-Daily-Candles-Volumes\2018\04\Loop.681'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AABruce.1.0/One-Min-Daily-Candles-Volumes/2018/04/Loop.681.Reading file 2018-04-19-08-37---965005---1.Status Report.AABruce.One-Min-Daily-Candles-Volumes.2018.04.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AABruce.1.0\One-Min-Daily-Candles-Volumes\2018\04\Loop.681\2018-04-18-21-04---559539---1.Indicator Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AABruce.1.0/One-Min-Daily-Candles-Volumes/2018/04/Loop.681.Reading file 2018-04-19-08-37---965005---1.Status Report.AABruce.One-Min-Daily-Candles-Volumes.2018.04.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AABruce.1.0\One-Min-Daily-Candles-Volumes\2018\04\Loop.681\2018-04-18-21-04---559539---1.Indicator Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AABruce.1.0/One-Min-Daily-Candles-Volumes/2018/04/Loop.681.Reading file 2018-04-19-08-37---965005---1.Status Report.AABruce.One-Min-Daily-Candles-Volumes.2018.04.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AABruce.1.0\One-Min-Daily-Candles-Volumes\2018\04\Loop.681\2018-04-18-21-04---559539---1.Indicator Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AABruce.1.0/One-Min-Daily-Candles-Volumes/2018/04/Loop.681.Reading file 2018-04-19-08-37---965005---1.Status Report.AABruce.One-Min-Daily-Candles-Volumes.2018.04.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AABruce.1.0\One-Min-Daily-Candles-Volumes\2018\04\Loop.681\2018-04-18-21-04---559539---1.Indicator Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AABruce.1.0/One-Min-Daily-Candles-Volumes/2018/04/Loop.681.Reading file 2018-04-19-08-37---916174---1.Blob Storage.AAMasters.AACharly.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AABruce.1.0\One-Min-Daily-Candles-Volumes\2018\04\Loop.681\2018-04-18-21-04---559539---1.Indicator Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AABruce.1.0/One-Min-Daily-Candles-Volumes/2018/04/Loop.681.Reading file 2018-04-19-08-37---965005---1.Status Report.AABruce.One-Min-Daily-Candles-Volumes.2018.04.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AABruce.1.0\One-Min-Daily-Candles-Volumes\2018\04\Loop.681\2018-04-18-21-04---559539---1.Indicator Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Indicator/AABruce.1.0/One-Min-Daily-Candles-Volumes/2018/04/Loop.681.Reading file 2018-04-19-08-37---965005---1.Status Report.AABruce.One-Min-Daily-Candles-Volumes.2018.04.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Indicator\AABruce.1.0\One-Min-Daily-Candles-Volumes\2018\04\Loop.681\2018-04-18-21-04---559539---1.Indicator Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Hole-Fixing/2018/07/Loop.685.Reading file 2018-04-19-08-37---191362---1.Status Report.AACharly.Poloniex-Hole-Fixing.2018.07.log. err.message = ENOTEMPTY: directory not empty, rmdir 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Hole-Fixing\2018\07\Loop.685'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Hole-Fixing/2018/07/Loop.685.Reading file 2018-04-19-08-37---191362---1.Status Report.AACharly.Poloniex-Hole-Fixing.2018.07.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Hole-Fixing\2018\07\Loop.685\2018-04-18-21-04---19013---1.Extraction Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Hole-Fixing/2018/07/Loop.685.Reading file 2018-04-19-08-37---933173---1.Status Report.AACharly.Poloniex-Historic-Trades.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Hole-Fixing\2018\07\Loop.685\2018-04-18-21-04---19013---1.Extraction Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Hole-Fixing/2018/07/Loop.685.Reading file 2018-04-19-08-37---933173---1.Status Report.AACharly.Poloniex-Historic-Trades.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Hole-Fixing\2018\07\Loop.685\2018-04-18-21-04---19013---1.Extraction Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Hole-Fixing/2018/07/Loop.685.Reading file 2018-04-19-08-37---933173---1.Status Report.AACharly.Poloniex-Historic-Trades.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Hole-Fixing\2018\07\Loop.685\2018-04-18-21-04---19013---1.Extraction Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Hole-Fixing/2018/07/Loop.685.Reading file 2018-04-19-08-37---933173---1.Status Report.AACharly.Poloniex-Historic-Trades.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Hole-Fixing\2018\07\Loop.685\2018-04-18-21-04---19013---1.Extraction Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Hole-Fixing/2018/07/Loop.685.Reading file 2018-04-19-08-37---913744---1.User Bot-2018-07.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Hole-Fixing\2018\07\Loop.685\2018-04-18-21-04---19013---1.Extraction Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Hole-Fixing/2018/07/Loop.685.Reading file 2018-04-19-08-37---933173---1.Status Report.AACharly.Poloniex-Historic-Trades.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Hole-Fixing\2018\07\Loop.685\2018-04-18-21-04---19013---1.Extraction Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Hole-Fixing/2018/07/Loop.685.Reading file 2018-04-19-08-37---615833---1.Utilities.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Hole-Fixing\2018\07\Loop.685\2018-04-18-21-04---19013---1.Extraction Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Hole-Fixing/2018/07/Loop.685.Reading file 2018-04-19-08-37---191362---1.Status Report.AACharly.Poloniex-Hole-Fixing.2018.07.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Hole-Fixing\2018\07\Loop.685\2018-04-18-21-04---19013---1.Extraction Bot Process Main Loop.log'
Error trying to log info into a file.
File: ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Live-Trades/Loop.0/2018-04-18-21-04---424292---1.Run.log
Error: ENOENT: no such file or directory, open 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Live-Trades\Loop.0\2018-04-18-21-04---424292---1.Run.log'
Error trying to log info into a file.
File: ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Live-Trades/Loop.0/2018-04-18-21-04---424292---1.Run.log
Error: ENOENT: no such file or directory, open 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Live-Trades\Loop.0\2018-04-18-21-04---424292---1.Run.log'
Error trying to log info into a file.
File: ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Live-Trades/Loop.0/2018-04-18-21-04---424292---1.Run.log
Error: ENOENT: no such file or directory, open 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Live-Trades\Loop.0\2018-04-18-21-04---424292---1.Run.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Live-Trades/Loop.682.Reading file 2018-04-19-08-37---198799---1.Status Report.AACharly.Poloniex-Live-Trades.log. err.message = ENOTEMPTY: directory not empty, rmdir 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Live-Trades\Loop.682'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Live-Trades/Loop.682.Reading file 2018-04-19-08-37---896663---1.Status Dependencies.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Live-Trades\Loop.682\2018-04-18-21-04---362789---1.Extraction Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Live-Trades/Loop.682.Reading file 2018-04-19-08-37---198799---1.Status Report.AACharly.Poloniex-Live-Trades.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Live-Trades\Loop.682\2018-04-18-21-04---362789---1.Extraction Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Live-Trades/Loop.682.Reading file 2018-04-19-08-37---198799---1.Status Report.AACharly.Poloniex-Live-Trades.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Live-Trades\Loop.682\2018-04-18-21-04---362789---1.Extraction Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Live-Trades/Loop.682.Reading file 2018-04-19-08-37---896663---1.Status Dependencies.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Live-Trades\Loop.682\2018-04-18-21-04---362789---1.Extraction Bot Process Main Loop.log'
Error trying to delete Loop Folder ../Logs/2018/04/18/21/04/AAMasters/Extraction/AACharly.1.0/Poloniex-Live-Trades/Loop.682.Reading file 2018-04-19-08-37---896663---1.Status Dependencies.log. err.message = EPERM: operation not permitted, lstat 'C:\Users\userbots\GitHub\AAMasters\Logs\2018\04\18\21\04\AAMasters\Extraction\AACharly.1.0\Poloniex-Live-Trades\Loop.682\2018-04-18-21-04---362789---1.Extraction Bot Process Main Loop.log'

**Comment by Luis-Fernando-Molina** [comment]
Logs are not in files anymore.
